version: '3'
services:
  authentication:
    build: ./authentication
    ports:
      - "5000:5000"
    volumes:
      - ./Database/authentication:/python-api/instance
  product_service:
    build: ./Product_service
    ports:
      - "5010:5010"
    volumes:
      - ./Database/Product_service:/python-api/instance