apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "C:\\Users\\jatin\\OneDrive\\Documents\\deployment\\microservices-ecom"
