apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: divyanshkohli856/frontend1:t2
        ports:
        - containerPort: 3000
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: client-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: client
#   ports:
#   - port: 8081
#     targetPort: 3000
